#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.M3E >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.M3E=/luci-static/material3
		set luci.main.mediaurlbase=/luci-static/material3
		set luci.themes.M3E-Blue=/luci-static/material3-blue
		set luci.themes.M3E-Green=/luci-static/material3-green
		set luci.themes.M3E-Red=/luci-static/material3-red
		commit luci
	EOF
fi

exit 0