name: build-packages

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-24_10-ipk:
    name: openwrt-24.10 (ipk)
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          path: ${{ github.event.repository.name }}

      - name: build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: x86_64-openwrt-24.10
          PACKAGES: ${{ github.event.repository.name }}
          NO_REFRESH_CHECK: true

      - name: upload
        uses: actions/upload-artifact@v5
        with:
          name: openwrt-24.10-ipk
          path: |
            bin/packages/x86_64/action/*.ipk
          if-no-files-found: error

  build-snapshot-apk:
    name: SNAPSHOT (apk)
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          path: ${{ github.event.repository.name }}

      - name: build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: x86_64-SNAPSHOT
          PACKAGES: ${{ github.event.repository.name }}
          NO_REFRESH_CHECK: true

      - name: upload
        uses: actions/upload-artifact@v5
        with:
          name: snapshot-apk
          path: |
            bin/packages/x86_64/action/*.apk
          if-no-files-found: error