name: build-packages

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: ${{ matrix.branch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            branch: openwrt-24.10
            artifact_name: openwrt-24.10-ipk
            package_glob: '*.ipk'
          - arch: x86_64
            branch: SNAPSHOT
            artifact_name: snapshot-apk
            package_glob: '*.apk'

    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          path: ${{ github.event.repository.name }}

      - name: build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.branch }}
          PACKAGES: ${{ github.event.repository.name }}
          NO_REFRESH_CHECK: true

      - name: upload
        uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            bin/packages/${{ matrix.arch }}/action/${{ matrix.package_glob }}
          if-no-files-found: error